### ISSUE TITLE
Reactor error at line 281

### ISSUE THREAD

**Issue by Anora** [Erani0/Draconic-Reactor-Controll#1]
Reactor: 281 : attempt to index ? (a nil value)
Draconic Evolutiuon version 2.3.24.349
computercraft 1.80pr1

**Comment by Erani0** [comment]
Use This version from Computercraft
[CC: Tweaked from curseforge](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked/files/2992872)

**Comment by Anora** [comment]
thanks much, should point out to  cc: tweaked in the how to
