### ISSUE TITLE
Reactor:184: attempt to compare nil whit number

### ISSUE THREAD

**Issue by Anora** [Erani0/Draconic-Reactor-Controll#2]
https://www.dropbox.com/s/fi7ih86jpc8fx20/2021-07-22_13.51.12.png?dl=0

https://www.dropbox.com/s/jywxrp0h4k3k2ep/2021-07-22_13.54.01_2.png?dl=0

**Comment by Erani0** [comment]
Is this a custom modpack?
Send me please a Screenshot from your setup
